--1. FONEPAY_INWARD_IBFT_CBS : This table contains inward IBFT data from CBS
--2. FONEPAY_INWARD_IBFT : This table contains inward IBFT data from Fonepay Bank Switch

--SELECT * from iReporting..MOBILE_MONEY_IBFT_TRANSACTION WHERE CUSTOMER_ACCOUNT = '2701612095205001'

use iReporting

CREATE TABLE FONEPAY_INWARD_IBFT
(
TRANSACTION_ID varchar(25),
SESSION_SRL_NO varchar(25),
RECORDED_DATE datetime,
INSTRUCTION_ID varchar(50),
AMOUNT money,
DEBIT_BANKSWITCH_AUDIT_NUMBER_FIELD_11 varchar(25),
DEBTOR_BANK varchar(50),
SENDER_MOBILE_NUMBER varchar(50),
DEBTOR_NAME varchar(50),
DEBIT_STATUS varchar(25),
DEBIT_REASON_CODE varchar(25),
DEBIT_MESSAGE varchar(50),
CREDITOR_BANK varchar(50),
CREDITOR_ACCOUNT varchar(25),
RECEIVER_NAME varchar(100),
CREDIT_STATUS varchar(25),
CREDIT_REASON_CODE varchar(50),
CREDIT_MESSAGE varchar(50),
SETTLEMENT_DATE datetime,
SETTLEMENT_STATUS varchar(50),
SETTLEMENT_REVERSAL varchar(50),
IS_RTGS varchar(25),
CHARGE_AMOUNT money,
CHARGE_LIABILITY varchar(25),
DEBIT_REVERSAL varchar(25),
DEBIT_REVERSAL_DATE datetime,
CREDIT_AUDIT_NUMBER varchar(25),
CATEGORY_PURPOSE varchar(25)
)


SELECT top 1 * FROM FONEPAY_INWARD_IBFT

--truncate table FONEPAY_INWARD_IBFT

select cast(RECORDED_DATE as date) RECORDED_DATE, count(*) as cnt from FONEPAY_INWARD_IBFT 
group by cast(RECORDED_DATE as date)
order by RECORDED_DATE asc


SELECT top 1 * FROM FONEPAY_INWARD_IBFT order by RECORDED_DATE DESC -- 14219250110005  (Parking Account)


-- DROP TABLE FONEPAY_INWARD_IBFT_CBS

CREATE TABLE FONEPAY_INWARD_IBFT_CBS
(
ACCT_NAME VARCHAR(150),
FORACID VARCHAR(25),
PSTD_DATE DATETIME,
RCRE_TIME DATETIME,
PART_TRAN_TYPE VARCHAR(5),
ACID VARCHAR(25),
TRAN_DATE DATETIME,
TRAN_ID VARCHAR(25),
VALUE_DATE DATETIME,
TRAN_AMT MONEY,
TRAN_PARTICULAR VARCHAR(250),
TRAN_PARTICULAR_2 VARCHAR(250),
TRAN_RMKS VARCHAR(250)
)

ALTER TABLE FONEPAY_INWARD_IBFT_CBS ADD FONEPAY_UNIQUE_ID VARCHAR(25)

UPDATE FONEPAY_INWARD_IBFT_CBS SET FONEPAY_UNIQUE_ID = SUBSTRING(TRAN_PARTICULAR,10,9)

CREATE INDEX IX_FON ON FONEPAY_INWARD_IBFT_CBS(FONEPAY_UNIQUE_ID)

CREATE INDEX IX_F ON FONEPAY_INWARD_IBFT_CBS(FORACID, TRAN_DATE)

CREATE INDEX IX_FONE ON FONEPAY_INWARD_IBFT(TRANSACTION_ID, RECORDED_DATE)



SELECT * FROM FONEPAY_INWARD_IBFT

SELECT TRAN_PARTICULAR, SUBSTRING(TRAN_PARTICULAR,10,9) FROM FONEPAY_INWARD_IBFT_CBS



SELECT 
FI.CATEGORY_PURPOSE,
FI.SENDER_MOBILE_NUMBER,
FI.DEBTOR_BANK,
FI.DEBTOR_NAME,
FI.RECORDED_DATE,
FIC.FORACID AS RECEIVER_ACCOUNT,
FIC.ACCT_NAME AS RECEIVER_ACCT_NAME,
FIC.PART_TRAN_TYPE, 
FIC.TRAN_ID,
FIC.TRAN_DATE,
FIC.VALUE_DATE,
FIC.PSTD_DATE,
FIC.RCRE_TIME,
FIC.TRAN_AMT,
FIC.TRAN_PARTICULAR,
FIC.TRAN_PARTICULAR_2,
FIC.FONEPAY_UNIQUE_ID
FROM FONEPAY_INWARD_IBFT_CBS FIC
JOIN FONEPAY_INWARD_IBFT FI ON (FIC.FONEPAY_UNIQUE_ID = FI.TRANSACTION_ID) ORDER BY FIC.PSTD_DATE


SELECT * FROM FONEPAY_INWARD_IBFT_CBS ORDER BY TRAN_DATE


CREATE TABLE FONEPAY_INWARD_IBFT_TRANS
(
CATEGORY_PURPOSE VARCHAR(25),
SENDER_MOBILE_NUMBER VARCHAR(25),
DEBTOR_BANK VARCHAR(250),
DEBTOR_NAME VARCHAR(250),
RECORDED_DATE DATETIME,
RECEIVER_ACCOUNT VARCHAR(25),
RECEIVER_ACCT_NAME VARCHAR(250),
PART_TRAN_TYPE VARCHAR(25),
TRAN_ID VARCHAR(25),
TRAN_DATE DATETIME,
VALUE_DATE DATETIME,
PSTD_DATE DATETIME,
RCRE_TIME DATETIME,
TRAN_AMT MONEY,
TRAN_PARTICULAR VARCHAR(250),
TRAN_PARTICULAR_2 VARCHAR(250),
FONEPAY_UNIQUE_ID VARCHAR(25)
)


INSERT INTO FONEPAY_INWARD_IBFT_TRANS
SELECT 
FI.CATEGORY_PURPOSE,
FI.SENDER_MOBILE_NUMBER,
FI.DEBTOR_BANK,
FI.DEBTOR_NAME,
FI.RECORDED_DATE,
FIC.FORACID AS RECEIVER_ACCOUNT,
FIC.ACCT_NAME AS RECEIVER_ACCT_NAME,
FIC.PART_TRAN_TYPE, 
FIC.TRAN_ID,
FIC.TRAN_DATE,
FIC.VALUE_DATE,
FIC.PSTD_DATE,
FIC.RCRE_TIME,
FIC.TRAN_AMT,
FIC.TRAN_PARTICULAR,
FIC.TRAN_PARTICULAR_2,
FIC.FONEPAY_UNIQUE_ID
FROM FONEPAY_INWARD_IBFT_CBS FIC
JOIN FONEPAY_INWARD_IBFT FI ON (FIC.FONEPAY_UNIQUE_ID = FI.TRANSACTION_ID) ORDER BY FIC.PSTD_DATE


SELECT * FROM FONEPAY_INWARD_IBFT_TRANS -- final table for inward IBFT

/*
INSERT INTO FONEPAY_INWARD_CBS
SELECT * FROM OPENQUERY(FINLIVE,'
SELECT G.ACCT_NAME,G.FORACID,FONEPAYAC.* FROM 
(
SELECT ACID, TRAN_DATE, TRAN_ID, VALUE_DATE, TRAN_AMT, TRAN_PARTICULAR, TRAN_PARTICULAR_2, TRAN_RMKS 
FROM TBAADM.HTD WHERE 
(TO_CHAR(TRAN_DATE,''YYYY-MM-DD'') >= ''2025-05-11'' AND TO_CHAR(TRAN_DATE,''YYYY-MM-DD'') <= ''2025-05-25'') 
AND ACID = ''TX2344962''
AND PART_TRAN_TYPE = ''D'' 
) FONEPAYAC
JOIN TBAADM.HTD H ON (FONEPAYAC.TRAN_ID = H.TRAN_ID AND FONEPAYAC.TRAN_DATE = H.TRAN_DATE)
JOIN TBAADM.GAM G ON (G.ACID = H.ACID) WHERE H.PART_TRAN_TYPE = ''D'' 
AND (TO_CHAR(H.TRAN_DATE,''YYYY-MM-DD'') = ''2025-05-25'') 
')
*/



SELECT * FROM FONEPAY_INWARD_IBFT_CBS

SELECT * FROM FONEPAY_INWARD_IBFT ORDER BY RECORDED_DATE DESC

SELECT * FROM FONEPAY_INWARD_IBFT_CBS

SELECT * FROM FONEPAY_INWARD_IBFT_CBS WHERE TRAN_PARTICULAR LIKE '%866718647%'



SELECT * FROM OPENQUERY(FINLIVE,'SELECT * FROM TBAADM.DTD WHERE ROWNUM <= 1')

Instruction ID : 'MNBBLNPKA-7949990'
Transaction ID : '866718647'
Amount : 2085.00


FON:IBFT:866718647:4440:LXBLNPKA:MNBBLNPKA:BASANTI

/*
SELECT
    r.blocking_session_id AS BlockingSessionID,
    r.session_id AS BlockedSessionID,
    r.wait_type,
    r.wait_time,
    r.wait_resource,
    r.last_wait_type,
    r.status,
    DB_NAME(r.database_id) AS DatabaseName,
    s.host_name,
    s.program_name,
    s.login_name,
    t.text AS QueryText
FROM sys.dm_exec_requests r
JOIN sys.dm_exec_sessions s ON r.session_id = s.session_id
CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) AS t
WHERE r.blocking_session_id <> 0;



SELECT OBJECT_ID('dbo.FONEPAY_INWARD_IBFT_CBS') AS ObjectID;


SELECT
    r.session_id,
    r.status,
    r.command,
    r.cpu_time,
    r.total_elapsed_time,
    s.host_name,
    s.program_name,
    s.login_name,
    t.text AS sql_text
FROM sys.dm_tran_locks l
JOIN sys.dm_exec_requests r ON l.request_session_id = r.session_id
JOIN sys.dm_exec_sessions s ON r.session_id = s.session_id
CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) t
WHERE l.resource_associated_entity_id = OBJECT_ID('dbo.FONEPAY_INWARD_IBFT_CBS');



KILL 90;


SELECT 
    r.session_id,
    r.status,
    r.command,
    t.text AS sql_text,
    s.login_name,
    s.host_name,
    s.program_name
FROM sys.dm_exec_requests r
JOIN sys.dm_exec_sessions s ON r.session_id = s.session_id
CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) t
WHERE r.session_id = 90;


SELECT 
    session_id, 
    percent_complete, 
    status, 
    command, 
    wait_type, 
    wait_time, 
    blocking_session_id
FROM sys.dm_exec_requests
WHERE session_id = 90;




SELECT 
    blocking_session_id AS blocker,
    session_id AS blocked,
    wait_type,
    wait_time,
    wait_resource
FROM sys.dm_exec_requests
WHERE blocking_session_id <> 0;



select * from esewa_withdrawal order by tran_date desc


select * from esewa_withdrawal WHere cast(TRAN_DATE AS DATE) = '2025-06-01'



select * from openquery(finlive,'select trunc(sysdate-64) from dual')

*/